version: "3.8" #docker-compose version

services:
  blog-fe-dev:
    # Set the container name
    container_name: blog-fe-dev_c

    # set name for the image
    image: blog-fe-dev_i

    # Build the image using the Dockerfile in the current context
    build:
      context: ../../
      dockerfile: Dockerfile
      target: init-source-code

      # Map host port 3000 to container port 3000
    ports:
      - "3000:3000" #<host_port>:<container_port/protocol_port>

    # Mount the current directory to /app in the container
    volumes:
      - ../../src:/source-code/src

    # Specify the command to run when the container starts
    command: pnpm run dev
